### ISSUE TITLE
undefined reference to `HostOS`

### ISSUE THREAD

**Issue by faxm0dem** [keyboardio/Kaleidoscope-Unicode#10]
Hi,

I followed the documentation, but I get this error message at compile time:

```
undefined reference to `HostOS`
```

also, using `KALEIDOSCOPE_INIT_PLUGINS(Unicode);` in the sketch produces:

```
error: expected constructor, destructor, or type conversion before '(' token
 KALEIDOSCOPE_INIT_PLUGINS(Unicode);
```

**Comment by algernon** [comment]
Ugh, yes... I forgot to update the documentation. There easiest thing for now, is to `#include "Kaleidoscope-HostOS.h"` in your sketch too, and add `HostOS` to the list of plugins.

I'll update the readme, and fix the compatibility layer later today - thanks for the report!
