### ISSUE TITLE
Unicode on windows

### ISSUE THREAD

**Issue by lldata** [keyboardio/Kaleidoscope-Unicode#5]
I have trouble getting the unicode input working on windows. 
It just enters the hex key as clear text.

http://www.fileformat.info/tip/microsoft/enter_unicode.htm
This link prescribes:

> This method works regardless of any of your language settings, but is the most cumbersome to type.
> Press and hold down the Alt key.
> Press the + (plus) key on the numeric keypad.
> Type the hexidecimal unicode value.
> Release the Alt key.
> Alas, this appears to require a registry setting. It was already set on my computer, but some readers report that this method didn't work for them, and this is probably why. If you don't know what the registry is, please don't try this. Under HKEY_Current_User/Control Panel/Input Method, set EnableHexNumpad to "1". If you have to add it, set the type to be REG_SZ.
>

**Comment by algernon** [comment]
I think that as of #8, this should be fixed, and on Windows, the plugin should be doing the steps outlined in the report. If it is still broken, please feel free to reopen.
